todo_list/config/routes.rb
Rails.application.routes.draw do
  resources :items do
    collection do
      get :active
      get :complete
    end

    member do
      post :activate
      post :complete
    end
  end

  root 'items#index'

end

todo_list/app/models/item.rb
class Item < ActiveRecord::Base

  validates :title, presence: true

  scope :completed, -> { where(:completed => true) }
  scope :active, -> { where(:completed => false) }

end

todo_list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo_list/app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render 'new'
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item
      @item.update(:completed => true)
      redirect_to items_path
    end
  end

  def active
    @active_items = Item.active
  end


  def complete
    @complete_items = Item.completed
  end

  def show
  end


  private
    def item_params
      params.require(:item).permit(:title, :completed)
    end
end

todo_list/app/helpers/application_helper.rb
module ApplicationHelper
end

todo_list/app/helpers/items_helper.rb
module ItemsHelper
end

todo_list/app/views/items/active.html.erb
<% @active_items.each do |ai| %>
  <p><%= ai.title%></p>
   <%= form_for ai, :url => item_path(ai.id) do |f| %>
            <%= f.submit 'Complete'%>
    <%end%>

<%end%>

todo_list/app/views/items/complete.html.erb
<% @complete_items.each do |ci| %>
 <p><%= ci.title%></p>
 <%end%>

todo_list/app/views/items/index.html.erb
<% @items.each do |item| %>
  <ul>
    <li><%= item.title %></li>
        <%if !item.completed%>
          <%= form_for item, :url => item_path(item.id) do |f| %>
            <%= f.submit 'Complete'%>
          <%end%>
        <%end%>
    </ul>
 <% end %>

todo_list/app/views/items/new.html.erb
<%= form_for :item, url: items_path do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

todo_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <%= link_to 'New Item', new_item_path %> |
  <%= link_to 'All Items', items_path %> |
  <%= link_to 'Active Items', active_items_path %> |
  <%= link_to 'Completed Items', complete_items_path %>
</header>
<body>

<%= yield %>

</body>
</html>